// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.13.0
// source: day_of_week/DayOfWeek.proto

package day_of_week_pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Days int32

const (
	Days_UNDEFINED Days = 0
	Days_MONDAY    Days = 1
	Days_TUESDAY   Days = 2
	Days_WEDNESDAY Days = 3
	Days_THURSDAY  Days = 4
	Days_FRIDAY    Days = 5
	Days_SATURDAY  Days = 6
	Days_SUNDAY    Days = 7
)

// Enum value maps for Days.
var (
	Days_name = map[int32]string{
		0: "UNDEFINED",
		1: "MONDAY",
		2: "TUESDAY",
		3: "WEDNESDAY",
		4: "THURSDAY",
		5: "FRIDAY",
		6: "SATURDAY",
		7: "SUNDAY",
	}
	Days_value = map[string]int32{
		"UNDEFINED": 0,
		"MONDAY":    1,
		"TUESDAY":   2,
		"WEDNESDAY": 3,
		"THURSDAY":  4,
		"FRIDAY":    5,
		"SATURDAY":  6,
		"SUNDAY":    7,
	}
)

func (x Days) Enum() *Days {
	p := new(Days)
	*p = x
	return p
}

func (x Days) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Days) Descriptor() protoreflect.EnumDescriptor {
	return file_day_of_week_DayOfWeek_proto_enumTypes[0].Descriptor()
}

func (Days) Type() protoreflect.EnumType {
	return &file_day_of_week_DayOfWeek_proto_enumTypes[0]
}

func (x Days) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Days.Descriptor instead.
func (Days) EnumDescriptor() ([]byte, []int) {
	return file_day_of_week_DayOfWeek_proto_rawDescGZIP(), []int{0}
}

type DayOfWeek struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Day Days `protobuf:"varint,1,opt,name=day,proto3,enum=day_of_week.Days" json:"day,omitempty"`
}

func (x *DayOfWeek) Reset() {
	*x = DayOfWeek{}
	if protoimpl.UnsafeEnabled {
		mi := &file_day_of_week_DayOfWeek_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DayOfWeek) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DayOfWeek) ProtoMessage() {}

func (x *DayOfWeek) ProtoReflect() protoreflect.Message {
	mi := &file_day_of_week_DayOfWeek_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DayOfWeek.ProtoReflect.Descriptor instead.
func (*DayOfWeek) Descriptor() ([]byte, []int) {
	return file_day_of_week_DayOfWeek_proto_rawDescGZIP(), []int{0}
}

func (x *DayOfWeek) GetDay() Days {
	if x != nil {
		return x.Day
	}
	return Days_UNDEFINED
}

var File_day_of_week_DayOfWeek_proto protoreflect.FileDescriptor

var file_day_of_week_DayOfWeek_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x64, 0x61, 0x79, 0x5f, 0x6f, 0x66, 0x5f, 0x77, 0x65, 0x65, 0x6b, 0x2f, 0x44, 0x61,
	0x79, 0x4f, 0x66, 0x57, 0x65, 0x65, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x64,
	0x61, 0x79, 0x5f, 0x6f, 0x66, 0x5f, 0x77, 0x65, 0x65, 0x6b, 0x22, 0x30, 0x0a, 0x09, 0x44, 0x61,
	0x79, 0x4f, 0x66, 0x57, 0x65, 0x65, 0x6b, 0x12, 0x23, 0x0a, 0x03, 0x64, 0x61, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x64, 0x61, 0x79, 0x5f, 0x6f, 0x66, 0x5f, 0x77, 0x65,
	0x65, 0x6b, 0x2e, 0x44, 0x61, 0x79, 0x73, 0x52, 0x03, 0x64, 0x61, 0x79, 0x2a, 0x71, 0x0a, 0x04,
	0x44, 0x61, 0x79, 0x73, 0x12, 0x0d, 0x0a, 0x09, 0x55, 0x4e, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45,
	0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x4f, 0x4e, 0x44, 0x41, 0x59, 0x10, 0x01, 0x12,
	0x0b, 0x0a, 0x07, 0x54, 0x55, 0x45, 0x53, 0x44, 0x41, 0x59, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09,
	0x57, 0x45, 0x44, 0x4e, 0x45, 0x53, 0x44, 0x41, 0x59, 0x10, 0x03, 0x12, 0x0c, 0x0a, 0x08, 0x54,
	0x48, 0x55, 0x52, 0x53, 0x44, 0x41, 0x59, 0x10, 0x04, 0x12, 0x0a, 0x0a, 0x06, 0x46, 0x52, 0x49,
	0x44, 0x41, 0x59, 0x10, 0x05, 0x12, 0x0c, 0x0a, 0x08, 0x53, 0x41, 0x54, 0x55, 0x52, 0x44, 0x41,
	0x59, 0x10, 0x06, 0x12, 0x0a, 0x0a, 0x06, 0x53, 0x55, 0x4e, 0x44, 0x41, 0x59, 0x10, 0x07, 0x42,
	0x1c, 0x5a, 0x1a, 0x64, 0x61, 0x79, 0x5f, 0x6f, 0x66, 0x5f, 0x77, 0x65, 0x65, 0x6b, 0x3b, 0x64,
	0x61, 0x79, 0x5f, 0x6f, 0x66, 0x5f, 0x77, 0x65, 0x65, 0x6b, 0x5f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_day_of_week_DayOfWeek_proto_rawDescOnce sync.Once
	file_day_of_week_DayOfWeek_proto_rawDescData = file_day_of_week_DayOfWeek_proto_rawDesc
)

func file_day_of_week_DayOfWeek_proto_rawDescGZIP() []byte {
	file_day_of_week_DayOfWeek_proto_rawDescOnce.Do(func() {
		file_day_of_week_DayOfWeek_proto_rawDescData = protoimpl.X.CompressGZIP(file_day_of_week_DayOfWeek_proto_rawDescData)
	})
	return file_day_of_week_DayOfWeek_proto_rawDescData
}

var file_day_of_week_DayOfWeek_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_day_of_week_DayOfWeek_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_day_of_week_DayOfWeek_proto_goTypes = []interface{}{
	(Days)(0),         // 0: day_of_week.Days
	(*DayOfWeek)(nil), // 1: day_of_week.DayOfWeek
}
var file_day_of_week_DayOfWeek_proto_depIdxs = []int32{
	0, // 0: day_of_week.DayOfWeek.day:type_name -> day_of_week.Days
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_day_of_week_DayOfWeek_proto_init() }
func file_day_of_week_DayOfWeek_proto_init() {
	if File_day_of_week_DayOfWeek_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_day_of_week_DayOfWeek_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DayOfWeek); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_day_of_week_DayOfWeek_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_day_of_week_DayOfWeek_proto_goTypes,
		DependencyIndexes: file_day_of_week_DayOfWeek_proto_depIdxs,
		EnumInfos:         file_day_of_week_DayOfWeek_proto_enumTypes,
		MessageInfos:      file_day_of_week_DayOfWeek_proto_msgTypes,
	}.Build()
	File_day_of_week_DayOfWeek_proto = out.File
	file_day_of_week_DayOfWeek_proto_rawDesc = nil
	file_day_of_week_DayOfWeek_proto_goTypes = nil
	file_day_of_week_DayOfWeek_proto_depIdxs = nil
}
